  
name: deployResourcesCLI
on: 
  push:
    branches: master
jobs: 

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
          
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: deploy ML workspace
      uses: azure/CLI@v1 
      with:
        azcliversion: 2.9.1
        inlineScript: |
          az deployment group create --resource-group ${{ secrets.RESOURCE_GROUP }} --template-file .cloud/.azure/deploy.json \
          --parameters .cloud/.azure/deploy.params.json patToken=${{secrets.PATTOKEN}} repo_name=$GITHUB_REPOSITORY
